---
title: "Example of a Simulation Study using Randomly Generated IRT Data"
author: "Nina van Gerwen (1860852)"
date: "2022-10-28"
output: html_document
---

## Loading the functions

To load the functions, we use source() and choose the appropriate files. To 
find out how the functions work exactly, please look at the function files directly.

```{r IRF calculation functions}
## Data generation is based on three models, therefore we created functions for
## the calculations of every model (1PL - 2PL - 3PL)

source("Functions/model-calculations.R")
source("Functions/data-generation.R")
source("Functions/missingness.R")
source("Functions/fit-indices calculations.R")

```

## Generating IRT data

```{r}
set.seed(1248)
test <- data.gen(n = 100, k = 5, model = "2PL")
```

## Using generated IRT data in a simulation study

```{r}
## LTM to fit the required models
require(ltm)
## DPLYR for some tidying
require(dplyr)
## MAGRITTR for the pipe
require(magrittr)

test_length <- as.factor(c(5, 10, 20))
sample_size <- as.factor(c(200, 300, 500, 1000, 1500))

n_sim <- 10

## We vary three factors, and for the simulation study, we 
## cross-examine them through a nested for loop

tli_results <- data.frame(test_length = NA, sample_size = NA, TLI_M = NA,
                          TLI_SE = NA, CFI_M = NA, CFI_SE = NA)

set.seed(1248)

for(a in levels(test_length)){

  for(b in levels(sample_size)){
    
      tli_values <- rep(NA, n_sim)
      cfi_values <- rep(NA, n_sim)
      
      temp_n <- as.numeric(as.character(b))
      temp_k <- as.numeric(as.character(a))
      
        for(j in 1:n_sim){
        ## Then, for every condition, generate data according to the
        ## current condition

          temp_data <- data.gen(n = temp_n, k = temp_k, model = "3PL")
                        
          l_0 <- ltm(temp_data ~ z1, IRT.param = TRUE)$log.Lik
          
          aggr_data <- temp_data %>%
                        as.data.frame(.) %>%
                        mutate(fr = rep(1, temp_n)) %>%
                        aggregate(fr ~ ., data = ., sum)
          
          tli_values[j] <- TLI(l_0, temp_data, aggr_data, temp_n, temp_k)
          
          cfi_values[j] <- CFI(l_0, temp_data, aggr_data, temp_n, temp_k)
          
          print(tli_values[j])
        
        }
      
      tli_results <- rbind(tli_results, c(a, b, mean(tli_values), sd(tli_values),
                                          mean(cfi_values), sd(cfi_values)))

  }
  
}

tli_results <- tli_results[-1 ,]
rownames(tli_results) <- NULL


```


```{r}
sessionInfo()
```

        
        

